project_name: kube-api-categories
before:
  hooks:
    - go mod tidy
builds:
  - binary: kube-api-categories
    main: ./cmd/kube-api-categories
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/tohjustin/kube-api-categories/internal/version.buildDate={{ .Env.BUILD_DATE }}
      - -X github.com/tohjustin/kube-api-categories/internal/version.gitCommit={{ .Env.GIT_COMMIT }}
      - -X github.com/tohjustin/kube-api-categories/internal/version.gitTreeState={{ .Env.GIT_TREE_STATE }}
      - -X github.com/tohjustin/kube-api-categories/internal/version.gitVersion={{ .Env.GIT_VERSION }}
      - -X github.com/tohjustin/kube-api-categories/internal/version.gitVersionMajor={{ .Env.GIT_VERSION_MAJOR }}
      - -X github.com/tohjustin/kube-api-categories/internal/version.gitVersionMinor={{ .Env.GIT_VERSION_MINOR }}
archives:
  - files:
      - LICENSE.md
      - README.md
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^build(\\(.+\\))?:"
      - "^chore(\\(.+\\))?:"
      - "^ci(\\(.+\\))?:"
      - "^docs(\\(.+\\))?:"
      - "^perf(\\(.+\\))?:"
      - "^refactor(\\(.+\\))?:"
      - "^style(\\(.+\\))?:"
      - "^test(\\(.+\\))?:"
krews:
  - index:
      owner: tohjustin
      name: kubectl-plugins
      branch: master
      token: "{{ .Env.KREW_GITHUB_TOKEN }}"
    url_template: "http://github.mycompany.com/foo/bar/releases/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Justin Toh
      email: tohjustin@hotmail.com
    commit_msg_template: "Krew plugin update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/tohjustin/kube-api-categories
    short_description: Print the supported API resources their categories
    description: |
      This plugin prints a table of supported API resources their categories on
      the server.
